In [1]:
import pandas as pd
import numpy as np

In [2]:
ext_data=pd.read_excel("External_Cibil_Dataset.xlsx")
int_data=pd.read_excel("Internal_Bank_Dataset.xlsx")

In [3]:
ext_data.describe()

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,PL_utilization,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,Credit_Score
count,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,...,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000,51336.000000
mean,25668.500000,-8129.961314,-70020.091320,-70022.375838,1.573749,-70003.987085,13.521953,0.184977,0.480053,0.295076,...,-86556.225194,0.167874,0.190414,0.065182,0.170492,0.056302,-45127.943635,0.271116,0.052887,679.859222
std,14819.571046,27749.328514,45823.312757,45819.820741,4.165012,45847.976100,53.336976,0.710240,1.522210,1.027471,...,34111.414750,0.373758,0.376218,0.235706,0.350209,0.213506,49795.784556,0.444540,0.223810,20.502764
min,1.000000,-99999.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,...,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,0.000000,0.000000,469.000000
25%,12834.750000,46.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,...,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99999.000000,0.000000,0.000000,669.000000
50%,25668.500000,70.000000,-99999.000000,-99999.000000,0.000000,-99999.000000,0.000000,0.000000,0.000000,0.000000,...,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.333000,0.000000,0.000000,680.000000
75%,38502.250000,161.000000,8.000000,3.000000,1.000000,15.000000,10.000000,0.000000,0.000000,0.000000,...,-99999.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.164250,1.000000,0.000000,691.000000
max,51336.000000,6065.000000,35.000000,35.000000,74.000000,900.000000,900.000000,12.000000,28.000000,20.000000,...,1.708000,1.000000,1.000000,1.000000,1.000000,1.000000,173800.000000,1.000000,1.000000,811.000000

In [78]:
merged=pd.merge(ext_data,int_data,on='PROSPECTID',how='inner')

In [80]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51336 entries, 0 to 51335
Data columns (total 87 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PROSPECTID                    51336 non-null  int64
 1   time_since_recent_payment     51336 non-null  int64
 2   time_since_first_deliquency   51336 non-null  int64
 3   time_since_recent_deliquency  51336 non-null  int64
 4   num_times_delinquent          51336 non-null  int64
 5   max_delinquency_level         51336 non-null  int64
 6   max_recent_level_of_deliq     51336 non-null  int64
 7   num_deliq_6mts                51336 non-null  int64
 8   num_deliq_12mts               51336 non-null  int64
 9   num_deliq_6_12mts             51336 non-null  int64
 10  max_deliq_6mts                51336 non-null  int64
 11  max_deliq_12mts               51336 non-null  int64
 12  num_times_30p_dpd             51336 non-null  int64
 13  num_times_60p_dpd             51336 non-null  int64
 14  num_std                       51336 non-null  int64
 15  num_std_6mts                  51336 non-null  int64
 16  num_std_12mts                 51336 non-null  int64
 17  num_sub                       51336 non-null  int64
 18  num_sub_6mts                  51336 non-null  int64
 19  num_sub_12mts                 51336 non-null  int64
 20  num_dbt                       51336 non-null  int64
 21  num_dbt_6mts                  51336 non-null  int64
 22  num_dbt_12mts                 51336 non-null  int64
 23  num_lss                       51336 non-null  int64
 24  num_lss_6mts                  51336 non-null  int64
 25  num_lss_12mts                 51336 non-null  int64
 26  recent_level_of_deliq         51336 non-null  int64
 27  tot_enq                       51336 non-null  int64
 28  CC_enq                        51336 non-null  int64
 29  CC_enq_L6m                    51336 non-null  int64
 30  CC_enq_L12m                   51336 non-null  int64
 31  PL_enq                        51336 non-null  int64
 32  PL_enq_L6m                    51336 non-null  int64
 33  PL_enq_L12m                   51336 non-null  int64
 34  time_since_recent_enq         51336 non-null  int64
 35  enq_L12m                      51336 non-null  int64
 36  enq_L6m                       51336 non-null  int64
 37  enq_L3m                       51336 non-null  int64
 38  MARITALSTATUS                 51336 non-null  object
 39  EDUCATION                     51336 non-null  object
 40  AGE                           51336 non-null  int64
 41  GENDER                        51336 non-null  object
 42  NETMONTHLYINCOME              51336 non-null  int64
 43  Time_With_Curr_Empr           51336 non-null  int64
 44  pct_of_active_TLs_ever        51336 non-null  float64
 45  pct_opened_TLs_L6m_of_L12m    51336 non-null  float64
 46  pct_currentBal_all_TL         51336 non-null  float64
 47  CC_utilization                51336 non-null  float64
 48  CC_Flag                       51336 non-null  int64
 49  PL_utilization                51336 non-null  float64
 50  PL_Flag                       51336 non-null  int64
 51  pct_PL_enq_L6m_of_L12m        51336 non-null  float64
 52  pct_CC_enq_L6m_of_L12m        51336 non-null  float64
 53  pct_PL_enq_L6m_of_ever        51336 non-null  float64
 54  pct_CC_enq_L6m_of_ever        51336 non-null  float64
 55  max_unsec_exposure_inPct      51336 non-null  float64
 56  HL_Flag                       51336 non-null  int64
 57  GL_Flag                       51336 non-null  int64
 58  last_prod_enq2                51336 non-null  object
 59  first_prod_enq2               51336 non-null  object
 60  Credit_Score                  51336 non-null  int64
 61  Approved_Flag                 51336 non-null  object
 62  Total_TL                      51336 non-null  int64
 63  Tot_Closed_TL                 51336 non-null  int64
 64  Tot_Active_TL                 51336 non-null  int64
 65  Total_TL_opened_L6M           51336 non-null  int64
 66  Tot_TL_closed_L6M             51336 non-null  int64
 67  pct_tl_open_L6M               51336 non-null  float64
 68  pct_tl_closed_L6M             51336 non-null  float64
 69  pct_active_tl                 51336 non-null  float64
 70  pct_closed_tl                 51336 non-null  float64
 71  Total_TL_opened_L12M          51336 non-null  int64
 72  Tot_TL_closed_L12M            51336 non-null  int64
 73  pct_tl_open_L12M              51336 non-null  float64
 74  pct_tl_closed_L12M            51336 non-null  float64
 75  Tot_Missed_Pmnt               51336 non-null  int64
 76  Auto_TL                       51336 non-null  int64
 77  CC_TL                         51336 non-null  int64
 78  Consumer_TL                   51336 non-null  int64
 79  Gold_TL                       51336 non-null  int64
 80  Home_TL                       51336 non-null  int64
 81  PL_TL                         51336 non-null  int64
 82  Secured_TL                    51336 non-null  int64
 83  Unsecured_TL                  51336 non-null  int64
 84  Other_TL                      51336 non-null  int64
 85  Age_Oldest_TL                 51336 non-null  int64
 86  Age_Newest_TL                 51336 non-null  int64
dtypes: float64(16), int64(65), object(6)
memory usage: 34.1+ MB

In [84]:
cat_cols=merged.select_dtypes('object').columns

In [85]:
cat_cols

Index(['MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2',
       'first_prod_enq2', 'Approved_Flag'],
      dtype='object')

In [88]:
num_cols=merged.drop(cat_cols,axis=1).columns

In [89]:
num_cols

Index(['PROSPECTID', 'time_since_recent_payment',
       'time_since_first_deliquency', 'time_since_recent_deliquency',
       'num_times_delinquent', 'max_delinquency_level',
       'max_recent_level_of_deliq', 'num_deliq_6mts', 'num_deliq_12mts',
       'num_deliq_6_12mts', 'max_deliq_6mts', 'max_deliq_12mts',
       'num_times_30p_dpd', 'num_times_60p_dpd', 'num_std', 'num_std_6mts',
       'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt',
       'num_dbt_6mts', 'num_dbt_12mts', 'num_lss', 'num_lss_6mts',
       'num_lss_12mts', 'recent_level_of_deliq', 'tot_enq', 'CC_enq',
       'CC_enq_L6m', 'CC_enq_L12m', 'PL_enq', 'PL_enq_L6m', 'PL_enq_L12m',
       'time_since_recent_enq', 'enq_L12m', 'enq_L6m', 'enq_L3m', 'AGE',
       'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'pct_of_active_TLs_ever',
       'pct_opened_TLs_L6m_of_L12m', 'pct_currentBal_all_TL', 'CC_utilization',
       'CC_Flag', 'PL_utilization', 'PL_Flag', 'pct_PL_enq_L6m_of_L12m',
       'pct_CC_enq_L6m_of_L12m', 'pct_PL_enq_L6m_of_ever',
       'pct_CC_enq_L6m_of_ever', 'max_unsec_exposure_inPct', 'HL_Flag',
       'GL_Flag', 'Credit_Score', 'Total_TL', 'Tot_Closed_TL', 'Tot_Active_TL',
       'Total_TL_opened_L6M', 'Tot_TL_closed_L6M', 'pct_tl_open_L6M',
       'pct_tl_closed_L6M', 'pct_active_tl', 'pct_closed_tl',
       'Total_TL_opened_L12M', 'Tot_TL_closed_L12M', 'pct_tl_open_L12M',
       'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'Auto_TL', 'CC_TL',
       'Consumer_TL', 'Gold_TL', 'Home_TL', 'PL_TL', 'Secured_TL',
       'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL'],
      dtype='object')

In [90]:
df_encoded = pd.get_dummies(merged, columns=cat_cols, dtype=int)

In [98]:
len(df_encoded.columns)

108

In [99]:
y=df_encoded['Credit_Score']

In [100]:
df_encoded=df_encoded.drop('Credit_Score',axis=1)

In [101]:
correlation=df_encoded.corrwith(y)

In [104]:
correlation

PROSPECTID                     -0.008003
time_since_recent_payment       0.056669
time_since_first_deliquency    -0.186691
time_since_recent_deliquency   -0.186704
num_times_delinquent           -0.053259
                                  ...
first_prod_enq2_others          0.091281
Approved_Flag_P1                0.628461
Approved_Flag_P2                0.172427
Approved_Flag_P3               -0.258558
Approved_Flag_P4               -0.600580
Length: 107, dtype: float64

In [115]:
import pandas as pd

def get_top_n_features(corr_series, target_name, n=9):
    
    # Drop the target variable itself so it doesn't show up as the #1 feature (corr = 1.0)
    if target_name in corr_series:
        corr_series = corr_series.drop(target_name)
        
    # Get absolute values and sort descending
    top_n = corr_series.abs().sort_values(ascending=False).head(n)
    
    return top_n.index.tolist()

In [116]:
top_features=get_top_n_features(correlation,"Credit_Score")

In [117]:
top_features

['Approved_Flag_P1',
 'Approved_Flag_P4',
 'num_std_12mts',
 'num_std',
 'num_std_6mts',
 'pct_PL_enq_L6m_of_ever',
 'pct_PL_enq_L6m_of_L12m',
 'pct_tl_open_L12M',
 'AGE']

In [119]:
X=df_encoded[top_features]

In [121]:
X

,Approved_Flag_P1,Approved_Flag_P4,num_std_12mts,num_std,num_std_6mts,pct_PL_enq_L6m_of_ever,pct_PL_enq_L6m_of_L12m,pct_tl_open_L12M,AGE
0,0,0,11,21,5,0.0,0.0,0.000,48
1,0,0,0,0,0,0.0,0.0,1.000,23
2,0,0,10,10,5,0.0,0.0,0.250,40
3,0,0,5,5,4,0.0,0.0,1.000,34
4,1,0,16,53,4,0.0,0.0,0.000,48
...,...,...,...,...,...,...,...,...,...
51331,0,1,0,0,0,0.0,0.0,0.333,43
51332,1,0,6,6,4,0.0,0.0,0.500,31
51333,0,0,0,0,0,1.0,1.0,1.000,28
51334,0,0,0,0,0,0.0,0.0,0.500,25
51335,0,0,10,18,4,0.0,0.0,0.000,25

In [122]:
y

0        696
1        685
2        693
3        673
4        753
        ...
51331    650
51332    702
51333    661
51334    686
51335    681
Name: Credit_Score, Length: 51336, dtype: int64

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [125]:
x_train.to_csv('x_train.csv')
x_test.to_csv('x_test.csv')
y_train.to_csv('y_train.csv')
y_test.to_csv('y_test.csv')